definitions:
  admin.LoginRequest:
    properties:
      passwd:
        type: string
      user_name:
        type: string
    required:
    - passwd
    - user_name
    type: object
  admin.LoginResp:
    properties:
      token:
        type: string
    type: object
  dto.CreateOrderReq:
    properties:
      amount:
        type: integer
      channel:
        description: 充值渠道 alipay 支付宝 paypal
        type: string
      subject:
        description: 支付商品 vip 会员 amount 充值金额 chapter 购买章节
        type: string
      subject_id:
        type: integer
    type: object
  dto.CreateOrderRsp:
    properties:
      channel:
        description: 充值渠道 alipay 支付宝 paypal
        type: string
      order_id:
        type: string
      paypal_url:
        type: string
      qrcode:
        items:
          type: integer
        type: array
    type: object
  dto.LoginResp:
    properties:
      token:
        type: string
    type: object
  dto.Resp:
    properties:
      cate_id:
        type: integer
      code:
        type: integer
      cur_page:
        type: integer
      data: {}
      msg:
        type: string
      total:
        type: integer
    type: object
  dto.UserRequest:
    properties:
      code:
        type: string
      passwd:
        type: string
      phone:
        type: integer
    required:
    - code
    - passwd
    - phone
    type: object
  go_micro_service_novel.Category:
    properties:
      cate_id:
        type: integer
      channel:
        type: integer
      is_show:
        type: integer
      name:
        type: string
      sort:
        type: integer
    type: object
  go_micro_service_novel.Chapter:
    properties:
      chapter_id:
        type: integer
      content:
        type: string
      is_vip:
        type: integer
      novel_id:
        type: integer
      num:
        type: integer
      title:
        type: string
      words:
        type: integer
    type: object
  go_micro_service_novel.Note:
    properties:
      new_chapter:
        type: string
      new_num:
        type: integer
      novel_id:
        type: integer
      novel_name:
        type: string
      prev_chapter:
        type: string
      prev_num:
        type: integer
    type: object
  go_micro_service_novel.Novel:
    properties:
      author:
        type: string
      cate_id:
        type: integer
      category_id:
        type: integer
      category_name:
        type: string
      chapter_current:
        type: integer
      chapter_total:
        type: integer
      img:
        type: string
      intro:
        type: string
      likes:
        type: integer
      name:
        type: string
      new_chapter:
        type: string
      novel_id:
        type: integer
      sort:
        type: integer
      un_likes:
        type: integer
      updated_at:
        type: string
      words:
        type: integer
    type: object
  go_micro_service_user.UserInfo:
    properties:
      phone:
        type: integer
      user_id:
        type: integer
    type: object
  go_micro_srv_charge.Log:
    properties:
      amount:
        type: integer
      novel_id:
        type: integer
      novel_name:
        type: string
    type: object
host: http://www.scg130.cn
info:
  contact:
    email: scg130@163.com
    name: scg130
  description: micro
  title: micro
  version: "1.0"
paths:
  /admin/login:
    post:
      description: 登录
      parameters:
      - description: body参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/admin.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Resp'
            - properties:
                data:
                  $ref: '#/definitions/admin.LoginResp'
              type: object
      summary: 登录
      tags:
      - 用户中心
  /charge/create:
    post:
      description: 创建订单
      parameters:
      - description: body参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateOrderReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Resp'
            - properties:
                data:
                  $ref: '#/definitions/dto.CreateOrderRsp'
              type: object
      summary: 创建订单
      tags:
      - 订单
  /find/{phone}:
    get:
      description: 通过手机号查找用户
      parameters:
      - description: 手机号
        in: path
        name: phone
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Resp'
            - properties:
                data:
                  $ref: '#/definitions/go_micro_service_user.UserInfo'
              type: object
        "500":
          description: 服务异常
          schema:
            type: string
      summary: 查找用户
      tags:
      - 用户中心
  /login:
    post:
      description: 登录
      parameters:
      - description: body参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Resp'
            - properties:
                data:
                  $ref: '#/definitions/dto.LoginResp'
              type: object
      summary: 登录
      tags:
      - 用户中心
  /novel/buy_chapter:
    get:
      description: 购买章节
      parameters:
      - description: query参数
        in: query
        name: chapter_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Resp'
      summary: 购买章节
      tags:
      - novel
  /novel/buy_logs:
    get:
      description: 获取购买历史
      parameters:
      - description: query参数
        in: query
        name: page
        required: true
        type: integer
      - description: query参数
        in: query
        name: size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Resp'
            - properties:
                data:
                  $ref: '#/definitions/go_micro_srv_charge.Log'
              type: object
      summary: 获取购买历史
      tags:
      - novel
  /novel/cates:
    get:
      description: 分类列表
      parameters:
      - in: query
        name: cate_id
        type: integer
      - in: query
        name: chapter_id
        type: integer
      - in: query
        name: is_end
        type: integer
      - in: query
        name: name
        type: string
      - in: query
        name: novel_id
        type: integer
      - in: query
        name: num
        type: integer
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      - in: query
        name: type
        type: string
      - in: query
        name: words
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Resp'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/go_micro_service_novel.Category'
                  type: array
              type: object
      summary: 分类列表
      tags:
      - novel
  /novel/chapter:
    get:
      description: 获取章节
      parameters:
      - description: query参数
        in: query
        name: chapter_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Resp'
            - properties:
                data:
                  $ref: '#/definitions/go_micro_service_novel.Chapter'
              type: object
      summary: 获取章节
      tags:
      - novel
  /novel/chapters:
    get:
      description: 章节列表
      parameters:
      - in: query
        name: cate_id
        type: integer
      - in: query
        name: chapter_id
        type: integer
      - in: query
        name: is_end
        type: integer
      - in: query
        name: name
        type: string
      - in: query
        name: novel_id
        type: integer
      - in: query
        name: num
        type: integer
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      - in: query
        name: type
        type: string
      - in: query
        name: words
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Resp'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/go_micro_service_novel.Chapter'
                  type: array
              type: object
      summary: 章节列表
      tags:
      - novel
  /novel/join-book:
    get:
      description: 我的书架
      parameters:
      - in: query
        name: cate_id
        type: integer
      - in: query
        name: chapter_id
        type: integer
      - in: query
        name: is_end
        type: integer
      - in: query
        name: name
        type: string
      - in: query
        name: novel_id
        type: integer
      - in: query
        name: num
        type: integer
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      - in: query
        name: type
        type: string
      - in: query
        name: words
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Resp'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/go_micro_service_novel.Note'
                  type: array
              type: object
      summary: 加入书架
      tags:
      - novel
  /novel/list:
    get:
      description: 小说列表
      parameters:
      - in: query
        name: cate_id
        type: integer
      - in: query
        name: chapter_id
        type: integer
      - in: query
        name: is_end
        type: integer
      - in: query
        name: name
        type: string
      - in: query
        name: novel_id
        type: integer
      - in: query
        name: num
        type: integer
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      - in: query
        name: type
        type: string
      - in: query
        name: words
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Resp'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/go_micro_service_novel.Novel'
                  type: array
              type: object
      summary: 小说列表
      tags:
      - novel
  /novel/note/del:
    get:
      description: 删除阅读记录
      parameters:
      - in: query
        name: cate_id
        type: integer
      - in: query
        name: chapter_id
        type: integer
      - in: query
        name: is_end
        type: integer
      - in: query
        name: name
        type: string
      - in: query
        name: novel_id
        type: integer
      - in: query
        name: num
        type: integer
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      - in: query
        name: type
        type: string
      - in: query
        name: words
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Resp'
      summary: 删除阅读记录
      tags:
      - novel
  /novel/notes:
    get:
      description: 我的书架
      parameters:
      - in: query
        name: cate_id
        type: integer
      - in: query
        name: chapter_id
        type: integer
      - in: query
        name: is_end
        type: integer
      - in: query
        name: name
        type: string
      - in: query
        name: novel_id
        type: integer
      - in: query
        name: num
        type: integer
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      - in: query
        name: type
        type: string
      - in: query
        name: words
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Resp'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/go_micro_service_novel.Note'
                  type: array
              type: object
      summary: 我的书架
      tags:
      - novel
  /novel/novel:
    get:
      description: 获取小说详情
      parameters:
      - description: query参数
        in: query
        name: novel_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Resp'
            - properties:
                data:
                  $ref: '#/definitions/go_micro_service_novel.Novel'
              type: object
      summary: 获取小说详情
      tags:
      - novel
  /novel/search:
    get:
      description: 搜索
      parameters:
      - in: query
        name: cate_id
        type: integer
      - in: query
        name: chapter_id
        type: integer
      - in: query
        name: is_end
        type: integer
      - in: query
        name: name
        type: string
      - in: query
        name: novel_id
        type: integer
      - in: query
        name: num
        type: integer
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      - in: query
        name: type
        type: string
      - in: query
        name: words
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Resp'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/go_micro_service_novel.Novel'
                  type: array
              type: object
      summary: 搜索
      tags:
      - novel
  /register:
    post:
      description: 注册
      parameters:
      - description: body参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Resp'
        "500":
          description: 服务异常
          schema:
            type: string
      summary: 注册
      tags:
      - 用户中心
  /user_info:
    post:
      description: 获取用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Resp'
        "500":
          description: 服务异常
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - 用户中心
schemes:
- http
swagger: "2.0"
